version: '3.7'
services:
  doctor-doom:
    image: mrnim94/doctor-doom:latest
    container_name: doctor-doom
    restart: unless-stopped
    environment:
      - DOOM_PATH=/tmp
      - DOOM_EXPORT=/var/log
      - RULE_AGE=1d
      - RULE_SIZE=100M
      - RULE_NAME="*"
      - DOOM_CIRCLE="* * * * *"
