apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-doom
  labels:
    app: doctor-doom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-doom
  template:
    metadata:
      labels:
        app: doctor-doom
    spec:
      volumes:
        - name: file-service
          persistentVolumeClaim:
            claimName: pvc-file-service-smb
      containers:
      - name: doctor-doom
        image: mrnim94/doctor-doom:latest
        volumeMounts:
          - name: file-service
            mountPath: /app/downloaded
        env:
          - name: DOOM_PATH
            value: /app/downloaded
          - name: CIRCLE
            value: "* * * * *"
          - name: DOOM_EXPORT
            value: /var/log/doctor-doom
          - name: RULE_AGE
            value: "1d"
          - name: RULE_SIZE
            value: "0M"
          - name: RULE_NAME
            value: "*"
          - name: RULE_AND
            value: "true"
      nodeSelector:
        kubernetes.io/os: linux
